name: Snyk PR

on:
  pull_request:
    paths:
      - "build.sbt"

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk-pr.yml@main
    with:
      ORG: ~
      SEVERITY_THRESHOLD: critical
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
